apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .values.name }}
  labels:
          app: {{ .values.name }}
          version: v1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
            app: {{ .values.name }}
            version: v1
  template:
    metadata:
      labels:
              app: {{ .values.name }}
              version: v1
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ values.name }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .values.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 80
          envFrom:
                  - configMapRef:
                          name: {{ .values.name }}
      nodeSelector: 
                Slave-1: WOrker-1
