apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
        name: {{ .values.name }}
spec:
        host: {{ .values.name }}
        subsets:
        - name: v1
          labels:
                  version: v1
