apiVersion: v1
kind: Service
metadata:
  name: {{ .values.name }}
  labels:
          app: {{ .values.name }}
          service: {{ .values.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      name: http
  selector: {{ .values.name }}
