apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .values.name }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ values.gateway }}
  http:
  - match:
    - uri:
        prefix: /member/
    route:
    - destination:
        host: {{ .values.name }}
        port:
          number: 80
