apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: {{ include "brierley-member-api.fullname" . }}
spec:
  host: brierley-members-api
  subsets:
  - name: v1
    labels:
      version: v1
