apiVersion: v1
kind: Service
metadata:
  name: {{ include "brierley-member-api.fullname" . }}
  labels:
    app: brierley-memeber-api
    service: brierley-member-api
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "brierley-member-api.selectorLabels" . | nindent 4 }}
