apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "brierley-member-api.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - brierley-gateway
  http:
  - match:
    - uri:
        prefix: /member/
    route:
    - destination:
        host: brierley-members-api
        port:
          number: 80
